# Generated by Django 4.1.7 on 2023-05-04 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_payment_orderplaced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='order_data',
            new_name='ordered_data',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='bikash_order_id',
            new_name='razorpy_order_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='bikash_payment_id',
            new_name='razorpy_payment_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='bikash_payment_status',
            new_name='razorpy_payment_status',
        ),
    ]
